### PR TITLE
Added and applied author's styles for UI.

### PR DESCRIPTION
**Pull request by Ulyanov-programmer**
Updated pages:
- Index
- Registration
- Log in
- Account/Manage (Index and others)

Made common styles for _Layout.
Added layouts of HTML pages to develop their styles.

New UI (on real pages the text was translated):

NewInterfaceSH1
NewInterfaceSH2
NewInterfaceSH3
NewInterfaceSH4

### CODE REVIEW

**Comment by KurnakovMaksim** [comment]
Thanks!

Fix:
* Remove the commented out code (Specially came up with a version control system for this)
* Translate interface to English (I don't understand your language)

**Comment by Ulyanov-programmer** [comment]
We are both Russians, we both understand Russian, don't deceive me.

A commit with translation has been added.

**Comment by KurnakovMaksim** [comment]
:)

**Comment by KurnakovMaksim** [comment]
Fix logout button
1cos

Fix styles in User Profile
2cos

In StorytellerManager fix search bar
3cos

In StorytellerManager fix update panel
4cos

Everywhere except for the main page and registration there is a white background, correct that too.
5cos

Found no more bugs

**Comment by Ulyanov-programmer** [comment]
Yes, I have not worked on these pages yet, the styles there might not work correctly.
I'll try to fix it before Wednesday.

**Pull request merged**
